[package]
name = "trait"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "parse"
path = "src/parse.rs"

[[bin]]
name = "id"
path = "id.rs"

[[bin]]
name = "reader"
path = "reader.rs"

[[bin]]
name = "writer"
path = "src/writer.rs"

[dependencies]
regex = "1.5"
