[package]
name = "trait"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "parse"
path = "src/parse.rs"

[[bin]]
name = "writer"
path = "src/writer.rs"

[[bin]]
name = "parse_generics"
path = "src/parse_generics.rs"

[dependencies]
regex = "1.5"
