[workspace]

members = [
    "01_type_system",
    "02_trait",
    "03_sys_traits",
    "04_multi_owner",
    "05_smart_pointers",
    "06_data_structure",
    "07_hash_table",
    "08_closure",
    "09_kv",
    "10_rgrep",
    "queryer",
    "thumbor",
    "ownership",
    "borrow"
]
